### ISSUE TITLE
Compilation of µWebSockets has failed

### ISSUE THREAD

**Issue by sw1sh** [loomnetwork/loom-js-samples#1]
The error appears at `yarn start` step on macOS.
I've fixed it for now with changing line in `node_modules/qaap-uws/uws.js`:
from this:
```return require(`./uws_${process.platform}_${process.versions.modules}`);```
to this:
```return require(`uws/uws_${process.platform}_${process.versions.modules}.node`);```

**Comment by mattkanwisher** [comment]
Seems to be an issue with Node 10 only Node 9 works. Need to dig in further

**Comment by Oxyaction** [comment]
OSX High Sierra 10.13.3
node **v10.1.0** didn't work with both npm and yarn (qaap-uws stucks in compilation)
than switched to node **v9.3.0** tried with yarn - still doesn't compile,
with npm compiled fine

**Comment by mattkanwisher** [comment]
I recommend node 8

**Comment by myyan** [comment]
- hi guys, what's the function of this command ?
```
 "proto": "protoc --js_out=\"import_style=commonjs,binary:.\" helloworld.proto"
```
- can you explained it detailly?  , i just know proto buffer just like json format , and  helloworld.proto just a schema

**Comment by aTravelingN3rd** [comment]
I think I have the same error:

{ kind: 'error',
  url: 'ws://127.0.0.1:46657/websocket',
  error:
   { Error: connect ECONNREFUSED 127.0.0.1:46657
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 46657 } }
{ kind: 'error',
  url: 'ws://127.0.0.1:9999/queryws',
  error:
   { Error: connect ECONNREFUSED 127.0.0.1:9999
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 9999 } }

And it goes on forever

**Comment by enlight** [comment]
@aTravelingN3rd no your errors are unrelated, try using `ws://127.0.0.1:46658/websocket` and `ws://127.0.0.1:46658/queryws` instead, and if you still get these errors it must mean your `loom` node isn't actually running.
